Updating publications list
whitemech/whitemech.github.io pull request #188
Opened 2023-07-04 17:45 UTC by cipollone

2023-07-16 18:29 UTC, francescofuggitti requested changes
Thank you! I just made a couple of fixes

2023-07-16 18:29 UTC, francescofuggitti commented on publications.bib
> +
```suggestion

@article{icaps2023fc,
	author={Fuggitti, Francesco and Chakraborti, Tathagata},
	title={NL2LTL – a Python Package for Converting Natural Language (NL) Instructions to Linear Temporal Logic (LTL) Formulas},
	journal={{ICAPS}},
	year={2023},
        note={System Demonstration.},
        bibbase_note = {<span style="color: red">Best System Demonstration Runner-Up.</span>} 
}
```

2023-07-16 18:29 UTC, francescofuggitti commented on publications.bib
> +	author={Bonassi, Luigi and De Giacomo, Giuseppe and Favorito, Marco and Fuggitti, Francesco and Gerevini, Alfonso Emilio and Scala, Enrico},
```suggestion
	author={Bonassi, Luigi and {De Giacomo}, Giuseppe and Favorito, Marco and Fuggitti, Francesco and Gerevini, Alfonso Emilio and Scala, Enrico},
```

2023-07-16 18:29 UTC, francescofuggitti commented on publications.bib
> +	journal={Proceedings of the International Conference on Automated Planning and Scheduling},
```suggestion
	journal={Proceedings of the International Conference on Automated Planning and Scheduling ({ICAPS})},
```

2023-07-16 18:29 UTC, francescofuggitti commented on publications.bib
> +	author={Ronca, Alessandro and Knorozova, Nadezda Alexandrovna and De Giacomo, Giuseppe},
```suggestion
	author={Ronca, Alessandro and Knorozova, Nadezda Alexandrovna and {De Giacomo}, Giuseppe},
```

2023-07-16 18:29 UTC, francescofuggitti commented on publications.bib
> +	journal={Proceedings of the AAAI Conference on Artificial Intelligence (AAAI)},
```suggestion
	journal={Proceedings of the AAAI Conference on Artificial Intelligence ({AAAI})},
```

2023-07-16 18:29 UTC, francescofuggitti commented on publications.bib
> +  title        = {AIDA: A Tool for Resiliency in Smart Manufacturing},
```suggestion
  author       = {{De Giacomo}, Giuseppe and Favorito, Marco and Leotta, Francesco and Mecella, Massimo and Monti, Flavia and Silo, Luciana},
  title        = {{AIDA}: A Tool for Resiliency in Smart Manufacturing},
```

2023-07-16 18:29 UTC, francescofuggitti commented on publications.bib
> +  author={De Giacomo, Giuseppe and Favorito, Marco and Leotta, Francesco and Mecella, Massimo and Silo, Luciana},
```suggestion
  author={{De Giacomo}, Giuseppe and Favorito, Marco and Leotta, Francesco and Mecella, Massimo and Silo, Luciana},
```

2023-07-16 18:29 UTC, francescofuggitti commented on publications.bib
> +                  Giuseppe De Giacomo and
```suggestion
                  Giuseppe {De Giacomo} and
```

2023-07-16 18:29 UTC, francescofuggitti commented on publications.bib
> +                  Giuseppe De Giacomo and
```suggestion
                  Giuseppe {De Giacomo} and
```

2023-07-16 18:29 UTC, francescofuggitti commented on publications.bib
> +                  Giuseppe De Giacomo and
```suggestion
                  Giuseppe {De Giacomo} and
```

2023-07-16 18:29 UTC, francescofuggitti commented on publications.bib
> +                  Giuseppe De Giacomo},
```suggestion
                  Giuseppe {De Giacomo}},
```

2023-07-16 18:29 UTC, francescofuggitti commented on publications.bib
> +  title        = {Synthesis of Maximally Permissive Strategies for LTLf Specifications},
```suggestion
  title        = {Synthesis of Maximally Permissive Strategies for {LTLf} Specifications},
```

2023-07-16 18:29 UTC, francescofuggitti commented on publications.bib
> +                  Giuseppe De Giacomo},
```suggestion
                  Giuseppe {De Giacomo}},
```

2023-07-16 18:29 UTC, francescofuggitti commented on publications.bib
> +  author       = {Giuseppe De Giacomo and
```suggestion
  author       = {Giuseppe {De Giacomo} and
```

2023-07-16 18:29 UTC, francescofuggitti commented on publications.bib
> +  title        = {LTLf Synthesis as {AND-OR} Graph Search: Knowledge Compilation at Work},
```suggestion
  title        = {{LTLf} Synthesis as {AND-OR} Graph Search: Knowledge Compilation at Work},
```

2023-07-16 18:29 UTC, francescofuggitti commented on publications.bib
> +                  Giuseppe De Giacomo},
```suggestion
                  Gabriel {Paludo Licks} and
                  Giuseppe {De Giacomo}},
```

2023-07-16 18:29 UTC, francescofuggitti commented on publications.bib
> +  title        = {Markov Abstractions for {PAC} Reinforcement Learning in Non-Markov
```suggestion
  title        = {Markov Abstractions for {PAC} Reinforcement Learning in Non-Markovian
```

2023-07-16 18:29 UTC, francescofuggitti commented on publications.bib
> +                  Giuseppe De Giacomo},
```suggestion
  author       = {Ramon {Fraga Pereira} and
                  Andr{\'{e}} {Grahl Pereira} and
                  Frederico Messa and
                  Giuseppe {De Giacomo}},
```

2023-07-17 09:09 UTC, cipollone commented on publications.bib
> +  title        = {Markov Abstractions for {PAC} Reinforcement Learning in Non-Markov
Non-Markov seems correct here

2023-07-17 09:15 UTC, cipollone reviewed
Applied suggestions (groupings).

2023-07-17 16:23 UTC, francescofuggitti approved these changes
That's great!

2023-07-17 16:30 UTC, merged